### ISSUE TITLE
A possible array overflow in dgetrf.c

### ISSUE THREAD

**Issue by miraculin1** [DanielMartensson/EmbeddedLapack#10]
I encountered a hard_fault,I thought it is caused by a array overflow in dgetrf.c.
When entering the `dgetrf_` function, a pointer(stored in stack when compiled with -O0) is modified toa non-valid address therefore later write to that pointer cause hard_fault. Code will run smoothly if I introduce any level of optimization since the pointer would be stored in the register, so the overflow would not affect.

**The caller:**
```c
// in EmbeddedLapack/src/Lapack/Src/dgetrf:124
    double IPIV_d[(int) *n]; // this was added 2019 due to memory loss of ipiv when using LU.c file
    dgetrf_(n, n, &a[a_offset], lda, &ipiv[1], info, IPIV_d);
    if (*info == 0) {
```
Here pass in `IPIV_d` is a `*n` dim array

**The callee:**
```c
// in EmbeddedLapack/src/Lapack/Src/dgetrf:215
    // Add to IPIV_d due to memory loss from ipiv when using LU.c file. 
    for(int i = 1; i <= min(*m, *n); i++)
	IPIV_d[i] = (double) ipiv[i];
```
Here `*m == *n` so `i` can be up to `*n` and overflow(I thought)

Project setup:
- A stm32f4 MCU, arm-none-eabi-gcc tool chain, linked with newlib
- not linking f2c(-lf2c)

Thanks for reading this, if I miss anything, sorry for any trouble caused by me, if possible plz let me know.

**Comment by DanielMartensson** [comment]
Hi @miraculin1 
Can you send a pull request ?

Also, use CControl instead. It has a rich library of linear algebra.

**Comment by miraculin1** [comment]
Thanks for reply,
I could try to make a pull request when I'm free after a few weeks.

Thanks for telling me that, I'd give a try!
