### ISSUE TITLE
How LAPACK is called?

### ISSUE THREAD

**Issue by tkhamvilai** [DanielMartensson/EmbeddedLapack#3]
Hello,

I'm new to LAPACK. I only know that it can speed up your code, but I'm not sure how it works.

For example, I look into your LinearAlgebra/dot.c and it seems like you're directly multiplying an element of both array together. 

I cannot see how functions in Lapack/Scr/ are called even though they are included in LinearAlgebra/declareFunctions.h.

Could you explain to me how this library works? Does it do the operator overloading somewhere?

Best regards,

**Comment by DanielMartensson** [comment]
This library is just an interface for LAPACK. Just to make it much more simpler and more MATLAB-like. 

My goal is to make it easy to use LAPACK, but still fast enough. 

When it comes to simple math, I do it by my self. But when it comes to LU, SVD, QR and so on. I'm using lapack.
