### ISSUE TITLE
issues compiling from terminal

### ISSUE THREAD

**Issue by jsmartini** [DanielMartensson/EmbeddedLapack#6]
Hi,

I am trying to compile my application using gcc from the terminal in vscode. I keep getting undefined reference errors even with using the -lm flag

Using the src folder example and running 
gcc -lm main.c

/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `qpOASES_getSqrt':
main.c:(.text+0x27f): undefined reference to `sqrt'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `Indexlist_isMember':
main.c:(.text+0x31c): undefined reference to `Indexlist_getIndex'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `Bounds_setType':
main.c:(.text+0x440): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x46c): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `Bounds_setStatus':
main.c:(.text+0x4bf): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x4eb): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `Constraints_setType':
main.c:(.text+0x77c): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x7a8): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `Constraints_setStatus':
main.c:(.text+0x7fb): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x827): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblemB_getBounds':
main.c:(.text+0x9c3): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x9ef): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblemB_setOptions':
main.c:(.text+0xd6b): undefined reference to `OptionsCPY'
/usr/bin/ld: main.c:(.text+0xd7d): undefined reference to `Options_ensureConsistency'
/usr/bin/ld: main.c:(.text+0xd95): undefined reference to `QProblemB_setPrintLevel'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblemB_setH':
main.c:(.text+0xed0): undefined reference to `DenseMatrixCON'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblemB_setG':
main.c:(.text+0xf11): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0xf3d): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: main.c:(.text+0xf54): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0xf80): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblemB_setLB':
main.c:(.text+0xfe5): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x1011): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblemB_setLBn':
main.c:(.text+0x10c0): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x10ec): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: main.c:(.text+0x112d): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x1159): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblemB_setUB':
main.c:(.text+0x1192): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x11be): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblemB_setUBn':
main.c:(.text+0x1261): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x128d): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: main.c:(.text+0x12ce): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x12fa): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblemB_computeGivens':
main.c:(.text+0x1405): undefined reference to `sqrt'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_getBounds':
main.c:(.text+0x1585): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x15b1): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_setOptions':
main.c:(.text+0x192d): undefined reference to `OptionsCPY'
/usr/bin/ld: main.c:(.text+0x193f): undefined reference to `Options_ensureConsistency'
/usr/bin/ld: main.c:(.text+0x1957): undefined reference to `QProblem_setPrintLevel'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_setH':
main.c:(.text+0x1a92): undefined reference to `DenseMatrixCON'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_setG':
main.c:(.text+0x1ad3): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x1aff): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: main.c:(.text+0x1b16): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x1b42): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_setLB':
main.c:(.text+0x1ba7): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x1bd3): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_setLBn':
main.c:(.text+0x1c82): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x1cae): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: main.c:(.text+0x1cef): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x1d1b): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_setUB':
main.c:(.text+0x1d54): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x1d80): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_setUBn':
main.c:(.text+0x1e23): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x1e4f): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: main.c:(.text+0x1e90): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x1ebc): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_getConstraints':
main.c:(.text+0x1f53): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x1f7f): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: main.c:(.text+0x1f9f): undefined reference to `ConstraintsCPY'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_setA':
main.c:(.text+0x20c9): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x20f5): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: main.c:(.text+0x210f): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x213b): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: main.c:(.text+0x218e): undefined reference to `DenseMatrixCON'
/usr/bin/ld: main.c:(.text+0x21da): undefined reference to `DenseMatrix_times'
/usr/bin/ld: main.c:(.text+0x229c): undefined reference to `DenseMatrix_getRowNorm'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_setLBA':
main.c:(.text+0x2328): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x2354): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_setLBAn':
main.c:(.text+0x2411): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x243d): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: main.c:(.text+0x247d): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x24a9): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_setUBA':
main.c:(.text+0x24f1): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x251d): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: /tmp/ccq6aT7Z.o: in function `QProblem_setUBAn':
main.c:(.text+0x25ce): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x25fa): undefined reference to `MessageHandling_throwError'
/usr/bin/ld: main.c:(.text+0x263a): undefined reference to `qpOASES_getGlobalMessageHandler'
/usr/bin/ld: main.c:(.text+0x2666): undefined reference to `MessageHandling_throwError'
collect2: error: ld returned 1 exit status

this is the output. 

Probably a bone head problem, but any help is appreciated!

Thanks,
Jon

**Comment by DanielMartensson** [comment]
Sorry for late reply. Can you post your code? 

Do you have `math.h` included? You are getting the error  `undefined reference to sqrt'`
