### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by VitorCMatias** [DanielMartensson/EmbeddedLapack#7]
Hello I followed the instructions rules of your setup, in the stmcube IDE and I receive the following  error messenge:

`Description Resource Path Location Type make: *** No rule to make target 'C:/Users/xxxxx/EmbeddedLapack-master/EmbeddedLapack/src/LinearAlgebra/add.c', needed by 'Core/Src/LinearAlgebra/add.o'.  Stop. final C/C++ Problem`

**Comment by DanielMartensson** [comment]
> Hello I followed the instructions rules of your setup, in the stmcube IDE and I receive the following error messenge:
> 
> `Description Resource Path Location Type make: *** No rule to make target 'C:/Users/xxxxx/EmbeddedLapack-master/EmbeddedLapack/src/LinearAlgebra/add.c', needed by 'Core/Src/LinearAlgebra/add.o'. Stop. final C/C++ Problem`

Hello @VitorCMatias 

Try Eclipse IDE and import it as existing project?

If you are using STM32 Cube IDE, then I suggest CControl instead. It do the same math stuff, but it's fitted for really small embedded systems such as ST-processors.
