### ISSUE TITLE
Building problems

### ISSUE THREAD

**Issue by Codedial06** [DanielMartensson/EmbeddedLapack#9]
Hi,

becausing "making" failed, I tried using your code in Eclipse according to the second method (installing on embedded target) but I get these errors: 

![image](https://user-images.githubusercontent.com/37216109/233097593-0f9e1cff-c53b-4913-bab1-d245bbdb03b5.png)

So building fails please help me

**Comment by DanielMartensson** [comment]
Hi! I till try to include SVD algorithms of this repository to CControl. CControl is much easier to build.
